name: Install Nginx

on:
  push:
    branches:
      - main

jobs:
  install-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Nginx
      run: |
        sudo apt-get update
        sudo apt-get install -y nginx

    - name: Start Nginx
      run: sudo service nginx start
